=== bulsu-miggy/bsit3b-bustos-finalproject/HOTEL-DY-GRANDE/HOTEL-DY-GRANDE/xmlfiles/AllRooms.dtd
<!ELEMENT rooms (room+)>
<!ELEMENT room (ID, RoomType, RoomName, MaxAdult, MaxChild, RoomDesc, NoofBed, Image, RoomFacility)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT RoomType (#PCDATA)>
<!ELEMENT RoomName (#PCDATA)>
<!ELEMENT MaxAdult (#PCDATA)>
<!ELEMENT MaxChild (#PCDATA)>
<!ELEMENT RoomDesc (#PCDATA)>
<!ELEMENT NoofBed (#PCDATA)>
<!ELEMENT Image (#PCDATA)>
<!ELEMENT RoomFacility (#PCDATA)>

=== bulsu-miggy/bsit3b-bustos-finalproject/HOTEL-DY-GRANDE/xmlfiles/rooms.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rooms SYSTEM "AllRooms.dtd">
<rooms><room><ID>1</ID><RoomType>1</RoomType><RoomName>Single Room for one person</RoomName><MaxAdult>1</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A single room is for one person and contains a single bed, and will usually be quite small</RoomDesc><NoofBed>1</NoofBed><Image>r1.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet acces</RoomFacility></room><room><ID>2</ID><RoomType>2</RoomType><RoomName>Double Room</RoomName><MaxAdult>2</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A double room is a room intended for two people, usually a couple, to stay in. One person occupying a double room has to pay a supplement.</RoomDesc><NoofBed>2</NoofBed><Image>r2.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet acces</RoomFacility></room><room><ID>3</ID><RoomType>3</RoomType><RoomName>triple room</RoomName><MaxAdult>4</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A triple room is a hotel room that is made to comfortably accommodate three people. The triple room , simply called a triple, at times, may be configured with different bed sizes to ensure three hotel guests can be accommodated comfortably.</RoomDesc><NoofBed>3</NoofBed><Image>r3.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>4</ID><RoomType>4</RoomType><RoomName>Quad Room</RoomName><MaxAdult>6</MaxAdult><MaxChild>3</MaxChild><RoomDesc>A quad, when referring to hotel rooms, is a room that can accommodate four people. The quad room may be configured with different bed sizes to ensure four hotel guests can be accommodated comfortably:</RoomDesc><NoofBed>4</NoofBed><Image>r4.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Tour &amp; excursions,Airport transfers,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>5</ID><RoomType>5</RoomType><RoomName>Queen Room</RoomName><MaxAdult>2</MaxAdult><MaxChild>1</MaxChild><RoomDesc>A room with a queen-size bed. It may be occupied by one or more people (Size: 153 x 203 cm). King:</RoomDesc><NoofBed>1</NoofBed><Image>7edd3d2f392c4a07d107f07cbe764fa51582977081.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Tour &amp; excursions,Airport transfers,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>6</ID><RoomType>1</RoomType><RoomName>Single Room with Balcony</RoomName><MaxAdult>1</MaxAdult><MaxChild>2</MaxChild><RoomDesc>Each room is equipped with satellite TV, minibar and a tea/coffee maker. Ironing facilities are provided in all rooms.\r\n\r\nTreebo Select Royal Garden offers a well-equipped business centre. Guests can make travel arrangements at the tour desk.\r\n\r\nCheckers Restaurant serves a variety of Indian, Chinese and Continental dishes.</RoomDesc><NoofBed>1</NoofBed><Image>ca3de1cf40a0af9351083d4b0e95736c1583047692.jpg</Image><RoomFacility>24-Hour doctor on call</RoomFacility></room><room><ID>7</ID><RoomType>1</RoomType><RoomName>Single Room for one person</RoomName><MaxAdult>1</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A single room is for one person and contains a single bed, and will usually be quite small</RoomDesc><NoofBed>1</NoofBed><Image>r1.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet acces</RoomFacility></room><room><ID>8</ID><RoomType>2</RoomType><RoomName>Double Room</RoomName><MaxAdult>2</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A double room is a room intended for two people, usually a couple, to stay in. One person occupying a double room has to pay a supplement.</RoomDesc><NoofBed>2</NoofBed><Image>r2.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet acces</RoomFacility></room><room><ID>9</ID><RoomType>3</RoomType><RoomName>triple room</RoomName><MaxAdult>4</MaxAdult><MaxChild>2</MaxChild><RoomDesc>A triple room is a hotel room that is made to comfortably accommodate three people. The triple room , simply called a triple, at times, may be configured with different bed sizes to ensure three hotel guests can be accommodated comfortably.</RoomDesc><NoofBed>3</NoofBed><Image>r3.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>10</ID><RoomType>4</RoomType><RoomName>Quad Room</RoomName><MaxAdult>6</MaxAdult><MaxChild>3</MaxChild><RoomDesc>A quad, when referring to hotel rooms, is a room that can accommodate four people. The quad room may be configured with different bed sizes to ensure four hotel guests can be accommodated comfortably:</RoomDesc><NoofBed>4</NoofBed><Image>r4.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Tour &amp; excursions,Airport transfers,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>11</ID><RoomType>5</RoomType><RoomName>Queen Room</RoomName><MaxAdult>2</MaxAdult><MaxChild>1</MaxChild><RoomDesc>A room with a queen-size bed. It may be occupied by one or more people (Size: 153 x 203 cm). King:</RoomDesc><NoofBed>1</NoofBed><Image>7edd3d2f392c4a07d107f07cbe764fa51582977081.jpg</Image><RoomFacility>24-Hour room service,Free wireless internet access,Laundry service,Tour &amp; excursions,Airport transfers,Babysitting on request,24-Hour doctor on call,Meeting facilities</RoomFacility></room><room><ID>12</ID><RoomType>1</RoomType><RoomName>Single Room with Balcony</RoomName><MaxAdult>1</MaxAdult><MaxChild>2</MaxChild><RoomDesc>Each room is equipped with satellite TV, minibar and a tea/coffee maker. Ironing facilities are provided in all rooms.\r\n\r\nTreebo Select Royal Garden offers a well-equipped business centre. Guests can make travel arrangements at the tour desk.\r\n\r\nCheckers Restaurant serves a variety of Indian, Chinese and Continental dishes.</RoomDesc><NoofBed>1</NoofBed><Image>ca3de1cf40a0af9351083d4b0e95736c1583047692.jpg</Image><RoomFacility>24-Hour doctor on call</RoomFacility></room></rooms>
